# docker compose file for local development - mock vllm inference server
version: '3.8'

services:
  mock_vllm:
    build:
      context: ../..
      dockerfile: docker/local/mock_vllm.Dockerfile
    container_name: mock_vllm
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
