version: '3.8'

services:
  mock_vllm:
    build:
      context: ../..
      dockerfile: docker/local/mock_vllm.Dockerfile
    container_name: mock_vllm
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - vllm_network

  vllm_proxy:
    build:
      context: ../..
      dockerfile: docker/Dockerfile
    container_name: vllm_proxy
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mock_vllm
    networks:
      - vllm_network

networks:
  vllm_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16