services:
  vllm-proxy-deepseek:
    image: smstack/vllm-proxy:v0.2.0-rc3
    container_name: vllm-proxy-deepseek
    privileged: true
    ports:
      - "8000:8000"  # HTTP port
    environment:
      - WORKERS=4
    env_file:
      - .env.deepseek
    volume:
      - ./cert.pem:/tmp/cert/cert.pem
      - ./key.pem:/tmp/cert/key.pem
    depends_on:
      - vllm-deepseek

  vllm-proxy-llama:
    image: smstack/vllm-proxy:v0.2.0-rc3
    container_name: vllm-proxy-llama
    privileged: true
    ports:
      - "8001:8000"  # HTTP port
    environment:
      - WORKERS=4
    env_file:
      - .env.llama
    volume:
      - ./cert.pem:/tmp/cert/cert.pem
      - ./key.pem:/tmp/cert/key.pem
    depends_on:
      - vllm-llama

  vllm-deepseek:
    image: vllm/vllm-openai:v0.8.5
    container_name: vllm-deepseek
    runtime: nvidia
    ports:
      - "8002:8000"
    volumes:
      - /mnt:/mnt
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              device_ids: ["0","1","2","3","4","5","6"]
    shm_size: "8g"
    command: >
      --model ig1/r1-1776-AWQ
      --dtype auto
      --tensor-parallel-size 1
      --pipeline-parallel-size 7
      --gpu-memory-utilization 0.98
      --enable-chunked-prefill
      --enable-reasoning  
      --reasoning-parser deepseek_r1  
      --max-model-len 65536
    environment:
      - CUDA_VISIBLE_DEVICE=0,1,2,3,4,5,6

  vllm-llama:
    image: vllm/vllm-openai:v0.8.5
    container_name: vllm-llama
    runtime: nvidia
    ports:
      - "8003:8000"
    volumes:
      - /mnt:/mnt
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              device_ids: ["7"]
    command: >
      --model RedHatAI/Llama-4-Scout-17B-16E-Instruct-quantized.w4a16
      --dtype auto
      --max-model-len 64000
      --kv-cache-dtype fp8
      --gpu-memory-utilization 0.98
    environment:
      - CUDA_VISIBLE_DEVICE=0

  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.18
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://etcd:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.5.13
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      MILVUS_ROOT_PASSWORD: ${MILVUS_ROOT_PASSWORD}
      MINIO_ACCESS_KEY_ID: ${MINIO_ACCESS_KEY_ID}
      MINIO_SECRET_ACCESS_KEY: ${MINIO_SECRET_ACCESS_KEY}
    volumes:
      - ./milvus/milvus.yaml:/milvus/configs/milvus.yaml
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"

  milvus-cron:
    image: testinprod/panda-milvus-cron:v0.0.1
    container_name: milvus-cron
    command: ["python", "cron.py"]
    environment:
      - MILVUS_ROOT_PASSWORD=${MILVUS_ROOT_PASSWORD}
      - MILVUS_URI=http://standalone:19530
      - MILVUS_COLLECTION_NAME=panda_collection_v1
    depends_on:
      - "standalone"
