x-common: &common-config
  restart: always
  logging:
    driver: "json-file"
    options:
      max-size: "100m"
      max-file: "5"
  runtime: nvidia
  env_file:
    - .env

services:
  vllm-proxy:
    <<: *common-config
    image: smstack/vllm-proxy:latest
    container_name: vllm-proxy
    privileged: true
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
    ports:
      - "8000:8000"  # HTTPS port
    depends_on:
      - vllm

  vllm:
    <<: *common-config
    image: vllm/vllm-openai:v0.6.5
    container_name: vllm
    ports:
      - "8001:8000"
    volumes:
      - /mnt:/mnt
    command: >
      --model deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
      --max-model-len 4096
      --dtype float16
    # --gpu-memory-utilization 0.98
    # --enforce_eager